build:
  environment:
    php:
      version: 7.0.8

checks:
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true

tools:
  external_code_coverage:
    timeout: 3600
  php_code_coverage:
    enabled: true
  php_code_sniffer:
    enabled: false
  php_cpd:
    enabled: true
    excluded_dirs: ["build", "test", "vendor"]
  php_cs_fixer:
    enabled: false
  php_loc:
    enabled: true
    excluded_dirs: ["build", "test", "vendor"]
  php_mess_detector:
    enabled: true
    filter:
      paths: ["lib/*"]
  php_pdepend:
    enabled: true
    excluded_dirs: ["build", "test", "vendor"]
  php_analyzer:
    enabled: true
    filter:
      paths: ["lib/*", "test/*"]
  php_hhvm:
    enabled: true
    filter:
      paths: ["lib/*", "test/*"]
  sensiolabs_security_checker: true