build:
  project_setup:
    before:
      - 'cd /usr/src'
      - 'sudo apt-get update'
      - 'sudo apt-get install make build-essential autoconf automake bison re2c clang flex libicu-dev libgmp-dev libmpfr-dev libmpc-dev libc6-dev libxml2-dev'
      - './buildconf'
      - './configure --prefix=/usr --enable-maintainer-zts --with-openssl --enable-json=shared'
      - 'make -j8'
      - 'sudo make install'

checks:
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true

tools:
  external_code_coverage:
    timeout: 3600
  php_code_coverage:
    enabled: true
  php_code_sniffer:
    enabled: false
  php_cpd:
    enabled: true
    excluded_dirs: ["build", "test", "vendor"]
  php_cs_fixer:
    enabled: false
  php_loc:
    enabled: true
    excluded_dirs: ["build", "test", "vendor"]
  php_mess_detector:
    enabled: true
    filter:
      paths: ["lib/*"]
  php_pdepend:
    enabled: true
    excluded_dirs: ["build", "test", "vendor"]
  php_analyzer:
    enabled: true
    filter:
      paths: ["lib/*", "test/*"]
  php_hhvm:
    enabled: true
    filter:
      paths: ["lib/*", "test/*"]
  sensiolabs_security_checker: true