sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
    packages:
      - valgrind
      - php7.1-dev

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - sudo php composer.phar install --no-interaction

script:
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/001.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/002.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/003.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/004.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/005.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/006.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/007.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/008.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/009.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/010.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/011.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/012.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/013.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/014.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/015.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/016.phpt 2>&1 | grep -v ^"No stack."$
  - gdb -batch -ex "run" -ex "bt" -ex "quit" --args php tests/017.phpt 2>&1 | grep -v ^"No stack."$
  - sudo php composer.phar memtest

notifications:
  on_success: never
  on_failure: always