sudo: required

language:
  - php
  - c

php:
  - nightly

addons:
  apt:
    packages:
      - gdb
      - apport

install:
  - composer install --no-interaction

before_script:
  - ulimit -c unlimited -S
  - echo '/tmp/core%e.%p' | sudo tee /proc/sys/kernel/core_pattern
  - cat /proc/sys/kernel/core_pattern

script:
  - composer test

after_failure:
  - for i in /tmp/core*.*; do gdb /home/travis/.phpenv/versions/`php-config --version`/bin/php core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;

notifications:
  on_success: never
  on_failure: never