env: NGROK_TOKEN=XtVgwNXH74FDpQrfaHEe_2DWxWhAn8bDdNapA9DH98
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
    packages:
      - valgrind
      - php7.1-dev

before_install:
  - eval "$(curl -sL https://raw.github.com/fniephaus/travis-remote-shell/master/run.sh)"

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - sudo php composer.phar install --no-interaction

script:
  - sudo php composer.phar memtest

notifications:
  on_success: never
  on_failure: always