sudo: false

language:
  - php
  - c

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu precise main'
    packages:
      - gdb
      - php7.1-dev

before_install:
  - ulimit -c unlimited -S

install:
  - composer install --no-interaction

script:
  - composer test

after_failure:
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1)
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" php -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

notifications:
  on_success: never
  on_failure: never