sudo: required

language:
  - php
  - c

php:
  - nightly

addons:
  apt:
    packages:
      - gdb
      - apport

install:
  - composer install

before_script:
  - ulimit -c unlimited -S
  - echo '/tmp/core%e.%p' | sudo tee /proc/sys/kernel/core_pattern

script:
  - composer test

after_failure:
  - sudo bash .travis/after_failure.sh

notifications:
  on_success: never
  on_failure: never