sudo: required

language: cpp

addons:
  apt:
    packages:
      - valgrind

before_install:
  - sudo apt-get -y install make build-essential autoconf automake bison re2c clang flex libicu-dev libgmp-dev libmpfr-dev libmpc-dev libc6-dev libxml2-dev
  - cd /usr/src
  - sudo git clone https://github.com/php/php-src.git
  - cd php-src
  - sudo ./buildconf
  - sudo ./configure --prefix=/usr --with-config-file-path=/etc/php.ini --with-config-file-scan-dir=/etc/php.d --with-openssl
  - sudo make
  - sudo make install
  - cd /home/travis/build/lilt-php/lilt
  - php -v
  - php -m
  - ls -l

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar self-update
  - sudo php composer.phar install --no-interaction

before_script:
  - echo "extension=lilt.so" >> /etc/php.ini
  - php -m

script:
  - php composer.phar bench
  - php composer.phar test

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  on_success: never
  on_failure: always