sudo: required
dist: trusty
language: c

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
    packages:
      - php7.1-dev

before_install:
  - php -v

install:
  - sudo composer install --no-interaction

script:
  - composer bench
  - composer test
  - composer memtest

notifications:
  on_success: never
  on_failure: always