sudo: false

language:
  - php
  - c

php:
  - nightly

addons:
  apt:
    packages:
      - gdb

before_install:
  - ulimit -c unlimited -S

install:
  - composer install --no-interaction

script:
  - composer test

after_failure:
  - cat /proc/sys/kernel/core_pattern
  - COREFILE=$(find tests -maxdepth 1 -name "core*" | head -n 1)
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" php -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

notifications:
  on_success: never
  on_failure: never