sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
    packages:
      - php7.1-dev

before_install:
  - php -v

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - sudo php composer.phar install --no-interaction

script:
  - sudo php composer.phar bench
  - sudo php composer.phar test
  - sudo php composer.phar memtest

notifications:
  on_success: never
  on_failure: always