sudo: required

language: cpp

addons:
  apt:
    packages:
      - valgrind

before_install:
  - sudo apt-get -y install make build-essential autoconf automake bison re2c clang flex libicu-dev libgmp-dev libmpfr-dev libmpc-dev libc6-dev libxml2-dev
  - cd ../..
  - git clone https://github.com/php/php-src.git
  - cd php-src
  - ./buildconf
  - ./configure --prefix=/usr --with-config-file-path=/usr/php.ini --with-config-file-scan-dir=/usr/php.d --with-openssl
  - make
  - sudo make install
  - cd ext/json
  - phpize
  - ./configure
  - make && sudo make install
  - cd ../..
  - echo "extension=json.so" >> /usr/php.d/json.ini
  - cd ../lilt-php/lilt
  - php -v
  - php -m
  - ls -l

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar self-update
  - php composer.phar install --no-interaction --no-dev

before_script:
  - echo "extension=lilt.so" >> /usr/php.d/lilt.ini

script:
  - php composer.phar bench
  - php composer.phar test

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  on_success: never
  on_failure: always