language: php

php:
  - nightly

addons:
  apt:
    packages:
      - valgrind
      - gdb

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar self-update
  - php composer.phar install --no-interaction --no-dev

before_script:
  - echo "extension=lilt.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - gdb php
  - run composer.phar memtest
  - quit

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  on_success: never
  on_failure: always