language:
  - php
  - c

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
    packages:
      - gdb
      - valgrind
      - php7.1-dev

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - sudo php composer.phar install --no-interaction

script:
  - sudo sh .travis/run_tests.sh

after_failure:
  - sudo sh .travis/after_failure.sh

notifications:
  on_success: never
  on_failure: always