language: php

php:
  - nightly

addons:
  apt:
    packages:
      - valgrind

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - echo "extension=lilt.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer memtest

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  on_success: never
  on_failure: always