sudo: required
dist: trusty

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
    packages:
      - valgrind
      - php7.1-dev

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - sudo php composer.phar install --no-interaction

before_script:
  - phpenv config-add tests.ini

script:
  - .travis/run_tests.sh

after_failure:
  - .travis/after_failure.sh

notifications:
  on_success: never
  on_failure: always