sudo: false

language: php

php:
  - nightly

install:
  - composer self-update
  - composer require scrutinizer/ocular:dev-master
  - composer install

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  on_success: never
  on_failure: always