sudo: required
dist: trusty
language: c

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
    packages:
      - php7.1

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar self-update
  - sudo php composer.phar install --no-interaction

script:
  - sudo php -dextension=lilt.so composer.phar test

notifications:
  on_success: never
  on_failure: always