sudo: required

language:
  - php
  - c

php:
  - nightly

addons:
  apt:
    packages:
      - gdb
      - apport

install:
  - composer install --no-interaction

before_script:
  - ulimit -c unlimited -S
  - echo 'core%e.%p' | sudo tee /proc/sys/kernel/core_pattern
  - cat /proc/sys/kernel/core_pattern

script:
  - composer test

after_failure:
  - ls
  - ls tests
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1)
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" php -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

notifications:
  on_success: never
  on_failure: never