sudo: required

language: php

php:
  - nightly

install:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master
  - composer install --no-interaction

before_script:
  - echo "extension=lilt.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - $(php -r 'if (PHP_MAJOR_VERSION >= 7) echo "phpdbg -qrr"; else echo "php";') vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  on_success: never
  on_failure: always